# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
   buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(c5277b1c-b443-449d-ab11-558d79910ae6)'
    appType: 'webAppLinux'
    appName: 'vignesh'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'